=for :stopwords dists

=head1 Dist::Zilla::Plugin::Test::Pod::No404s

Add C<xt/release/pod-no404s.t>
(a standard L<Test::Pod::No404s> test)
to your dists.

See module POD for more information.

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2011 by Randy Stauner.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
